name: Scheduled notebook tests (ubuntu)
on:
  schedule:
    - cron: "0 0 * * 2" # Run every Tuesday at 12:00 AM UTC
  workflow_dispatch:
jobs:
  test-notebooks-ubuntu:
    uses: ./.github/workflows/test-notebooks.yml
    with:
      os: ubuntu-latest
    secrets: inherit
