name: examples-schedules-macos
on:
  schedule:
    - cron:  '0 0 * * 5' # Run every Friday at 12:00 AM UTC
  workflow_dispatch:
jobs:
############## NOTEBOOKS ##############
  test-notebooks-macos:
    uses: ./.github/workflows/notebooks.yml
    with:
      os: macos-latest
############## SCRIPTS ##############
  test-scripts-macos:
    uses: ./.github/workflows/scripts.yml
    with:
      os: macos-latest
